server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: member-for-login/signup/check-id/reissue
          predicates:
            - Path=/api/v1/member/login, /api/v1/member/signup, /api/v1/member/check-id, /api/v1/member/reissue
            - Method=POST,GET
          uri: http://localhost:8081
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /${segment}

        # 위의 uri 제외한 나머지 member 서비스의 요청 처리
        - id: member-all
          predicates:
            - Path=/api/v1/member/**
            - Method=POST,GET,PUT,DELETE,PATCH
          uri: http://localhost:8081
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/api/v1/(?<segment>.*), /${segment}


jwt:
  secret: ${JWT_SECRET_KEY}